#!/bin/bash

# Install every dotfile in your home directory
for directory in */; do
    cp -r ${directory%/}/. ~;
done

# Create symlinks to ~/bin/ files inside ~/.local/bin
for binfile in ~/bin/*; do
    ln -s -i $binfile ~/.local/bin;
done
