#!/bin/bash
#
# ----------------------------
# Customize XFCE look and feel
# ----------------------------

# Appearance
xfconf-query -c xsettings -p /Net/ThemeName -s "Matcha-dark-sea"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark-Maia"
xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "xcursor-breeze-snow"
xfconf-query -c xsettings -p /Gtk/FontName -s "Liberation Sans Regular 10"
xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "FiraCode Nerd Font Regular 10"
xfconf-query -c xsettings -p /Gtk/ButtonImages -s false
xfconf-query -c xfwm4 -p /general/theme -s "Matcha-dark-sea"
xfconf-query -c xfwm4 -p /general/button_layout -s "|HMC"
xfconf-query -c xfwm4 -p /general/click_to_focus -s true
xfconf-query -c xfwm4 -p /general/cycle_apps_only -s false
xfconf-query -c xfwm4 -p /general/cycle_draw_frame -s true
xfconf-query -c xfwm4 -p /general/cycle_hidden -s true
xfconf-query -c xfwm4 -p /general/cycle_minimized -s false
xfconf-query -c xfwm4 -p /general/cycle_minimum -s true
xfconf-query -c xfwm4 -p /general/cycle_preview -s false
xfconf-query -c xfwm4 -p /general/cycle_raise -s false
xfconf-query -c xfwm4 -p /general/cycle_tabwin_mode -s 0
xfconf-query -c xfwm4 -p /general/cycle_workspaces -s false
xfconf-query -c xfwm4 -p /general/easy_click -s Super

# Keyboard
xfconf-query -c keyboards -p /Default/KeyRepeat/Delay -s 245
xfconf-query -c keyboards -p /Default/KeyRepeat/Rate -s 35

# Keybindings
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/<Alt>Print" --type string -s "xfce4-screenshooter -w"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/Print" --type string -s "xfce4-screenshooter"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/<Shift>Print" --type string -s "xfce4-screenshooter -r"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/<Super>d" --type string -s "xfce4-popup-whiskermenu"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/<Super>l" --type string -s "xflock4"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/<Super>p" --type string -s "pavucontrol"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Alt>Tab" --type string -s "cycle_windows_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Alt><Shift>Tab" --type string -s "cycle_reverse_windows_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Alt>space" --type string -s "popup_menu_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Primary><Super>Down" --type string -s "tile_down_left_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Primary><Super>Left" --type string -s "tile_up_left_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Primary><Super>Right" --type string -s "tile_up_right_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Primary><Super>Up" --type string -s "tile_down_right_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>j" --type string -s "move_window_left_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>k" --type string -s "move_window_right_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>Page_Down" --type string -s "move_window_next_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>Page_Up" --type string -s "move_window_prev_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>Up" --type string -s "maximize_window_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Down" --type string -s "tile_down_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>j" --type string -s "left_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>k" --type string -s "right_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Left" --type string -s "tile_left_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Page_Down" --type string -s "next_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Page_Up" --type string -s "prev_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>q" --type string -s "close_window_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Right" --type string -s "tile_right_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Tab" --type string -s "switch_window_key"
xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Up" --type string -s "maximize_window_key"

# Panel configuration
xfconf-query -c xfce4-panel -p /panels/panel-0/autohide-behavior -s 0
xfconf-query -c xfce4-panel -p /panels/panel-0/background-style -s 0
xfconf-query -c xfce4-panel -p /panels/panel-0/disable-struts -s false
xfconf-query -c xfce4-panel -p /panels/panel-0/icon-size -s 0
xfconf-query -c xfce4-panel -p /panels/panel-0/length -s 100
xfconf-query -c xfce4-panel -p /panels/panel-0/length-adjust -s true
xfconf-query -c xfce4-panel -p /panels/panel-0/mode -s 0
xfconf-query -c xfce4-panel -p /panels/panel-0/position -s p=6;x=960;y=19
xfconf-query -c xfce4-panel -p /panels/panel-0/position-locked -s true
xfconf-query -c xfce4-panel -p /panels/panel-0/size -s 24

