#!/bin/bash
#
# ------------------------
# Post installation script
# ------------------------

ask() {
    # Function to ask questions
    #
    # source: https://gist.github.com/davejamesmiller/1965569
    local prompt default reply

    if [[ ${2:-} = 'Y' ]]; then
        prompt='Y/n'
        default='Y'
    elif [[ ${2:-} = 'N' ]]; then
        prompt='y/N'
        default='N'
    else
        prompt='y/n'
        default=''
    fi

    while true; do
        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo -n "$1 [$prompt] "
        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read -r reply </dev/tty
        # Default?
        if [[ -z $reply ]]; then
            reply=$default
        fi
        # Check if the reply is valid
        case "$reply" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}



clear
echo "

 ▄▄▄·      .▄▄ · ▄▄▄▄▄    ▪   ▐ ▄ .▄▄ · ▄▄▄▄▄ ▄▄▄· ▄▄▌  ▄▄▌      .▄▄ ·  ▄▄· ▄▄▄  ▪   ▄▄▄·▄▄▄▄▄
▐█ ▄█▪     ▐█ ▀. •██      ██ •█▌▐█▐█ ▀. •██  ▐█ ▀█ ██•  ██•      ▐█ ▀. ▐█ ▌▪▀▄ █·██ ▐█ ▄█•██
 ██▀· ▄█▀▄ ▄▀▀▀█▄ ▐█.▪    ▐█·▐█▐▐▌▄▀▀▀█▄ ▐█.▪▄█▀▀█ ██▪  ██▪      ▄▀▀▀█▄██ ▄▄▐▀▀▄ ▐█· ██▀· ▐█.▪
▐█▪·•▐█▌.▐▌▐█▄▪▐█ ▐█▌·    ▐█▌██▐█▌▐█▄▪▐█ ▐█▌·▐█ ▪▐▌▐█▌▐▌▐█▌▐▌    ▐█▄▪▐█▐███▌▐█•█▌▐█▌▐█▪·• ▐█▌·
.▀    ▀█▄▀▪ ▀▀▀▀  ▀▀▀     ▀▀▀▀▀ █▪ ▀▀▀▀  ▀▀▀  ▀  ▀ .▀▀▀ .▀▀▀      ▀▀▀▀ ·▀▀▀ .▀  ▀▀▀▀.▀    ▀▀▀

"


# Copy dotfiles
echo
if ask ":: Copy the dotfiles to your home folder?" Y; then
    echo "Copying dotfiles [...]"
    # Copy every dotfile in your home directory
    # (except dirs that start with an underscore)
    for directory in [^_]*/; do
        cp -r ${directory%/}/. ~;
    done
else
    echo "Skipping..."
fi

echo
if ask ":: Change shell to zsh?" Y; then
    chsh -s /usr/bin/zsh
else
    echo "Skipping..."
fi

echo
if ask ":: Configure keyboard to 'us altgr-intl caps:super'?" Y; then
    echo "Configuring keyboard [...]"
    localectl set-x11-keymap us "" altgr-intl caps:super
else
    echo "Skipping..."
fi

echo
if ask ":: Install Neovim plugins?" Y; then
    nvim -c "PlugInstall"
else
    echo "Skipping..."
fi

echo
if ask ":: Download and install mambaforge?" Y; then
    echo "Downloading mambaforge [...]"
    echo "  ** Remember to install in ~/.mambaforge **"
    curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
    bash Mambaforge-$(uname)-$(uname -m).sh
else
    echo "Skipping..."
fi

echo
if ask ":: Configure printing services?" Y; then
    # Source: https://wiki.manjaro.org/index.php?title=Printing
    sudo gpasswd -a $USER sys
    sudo systemctl enable --now cups.service
    sudo systemctl enable --now cups.socket
    sudo systemctl enable --now cups.path
else
    echo "Skipping..."
fi

echo
if ask ":: Configure SSD TRIM?" Y; then
    # Source: https://averagelinuxuser.com/manjaro-xfce-after-install/#10-enable-trim-for-ssd
    sudo systemctl enable fstrim.timer
    sudo systemctl start fstrim.timer
else
    echo "Skipping..."
fi

echo
if ask ":: Lower swappiness to 5?" Y; then
    sudo sysctl -w vm.swappiness=5
else
    echo "Skipping..."
fi


# ----------------------------
# Customize XFCE look and feel
# ----------------------------

echo
if ask ":: Customize XFCE appearance and keyboard shortcuts?" Y; then
    # Appearance
    xfconf-query -c xsettings -p /Net/ThemeName -s "Matcha-dark-sea"
    xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark-Maia"
    xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "xcursor-breeze-snow"
    xfconf-query -c xsettings -p /Gtk/FontName -s "Liberation Sans Regular 10"
    xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "FiraCode Nerd Font Regular 10"
    xfconf-query -c xsettings -p /Gtk/ButtonImages -s false

    # xfwm4
    xfconf-query -c xfwm4 -p /general/theme -s "Matcha-dark-sea"
    xfconf-query -c xfwm4 -p /general/title_font -s "Liberation Sans 9"
    xfconf-query -c xfwm4 -p /general/activate_action -s switch
    xfconf-query -c xfwm4 -p /general/borderless_maximize -s true
    xfconf-query -c xfwm4 -p /general/box_move -s false
    xfconf-query -c xfwm4 -p /general/box_resize -s false
    xfconf-query -c xfwm4 -p /general/button_layout -s "|HMC"
    xfconf-query -c xfwm4 -p /general/button_offset -s 0
    xfconf-query -c xfwm4 -p /general/button_spacing -s 0
    xfconf-query -c xfwm4 -p /general/click_to_focus -s true
    xfconf-query -c xfwm4 -p /general/cycle_apps_only -s false
    xfconf-query -c xfwm4 -p /general/cycle_draw_frame -s true
    xfconf-query -c xfwm4 -p /general/cycle_hidden -s true
    xfconf-query -c xfwm4 -p /general/cycle_minimized -s false
    xfconf-query -c xfwm4 -p /general/cycle_minimum -s false
    xfconf-query -c xfwm4 -p /general/cycle_preview -s false
    xfconf-query -c xfwm4 -p /general/cycle_raise -s false
    xfconf-query -c xfwm4 -p /general/cycle_tabwin_mode -s 0
    xfconf-query -c xfwm4 -p /general/cycle_workspaces -s false
    xfconf-query -c xfwm4 -p /general/double_click_action -s "maximize"
    xfconf-query -c xfwm4 -p /general/double_click_distance -s 5
    xfconf-query -c xfwm4 -p /general/double_click_time -s 250
    xfconf-query -c xfwm4 -p /general/easy_click -s Super
    xfconf-query -c xfwm4 -p /general/focus_delay -s 250
    xfconf-query -c xfwm4 -p /general/focus_hint -s true
    xfconf-query -c xfwm4 -p /general/focus_new -s true
    xfconf-query -c xfwm4 -p /general/frame_border_top -s 0
    xfconf-query -c xfwm4 -p /general/frame_opacity -s 100
    xfconf-query -c xfwm4 -p /general/full_width_title -s true
    xfconf-query -c xfwm4 -p /general/horiz_scroll_opacity -s false
    xfconf-query -c xfwm4 -p /general/inactive_opacity -s 100
    xfconf-query -c xfwm4 -p /general/maximized_offset -s 0
    xfconf-query -c xfwm4 -p /general/mousewheel_rollup -s true
    xfconf-query -c xfwm4 -p /general/move_opacity -s 100
    xfconf-query -c xfwm4 -p /general/placement_mode -s center
    xfconf-query -c xfwm4 -p /general/placement_ratio -s 60
    xfconf-query -c xfwm4 -p /general/popup_opacity -s 100
    xfconf-query -c xfwm4 -p /general/prevent_focus_stealing -s true
    xfconf-query -c xfwm4 -p /general/raise_delay -s 250
    xfconf-query -c xfwm4 -p /general/raise_on_click -s true
    xfconf-query -c xfwm4 -p /general/raise_on_focus -s false
    xfconf-query -c xfwm4 -p /general/raise_with_any_button -s true
    xfconf-query -c xfwm4 -p /general/repeat_urgent_blink -s false
    xfconf-query -c xfwm4 -p /general/resize_opacity -s 100
    xfconf-query -c xfwm4 -p /general/restore_on_move -s true
    xfconf-query -c xfwm4 -p /general/scroll_workspaces -s false
    xfconf-query -c xfwm4 -p /general/shadow_delta_height -s 0
    xfconf-query -c xfwm4 -p /general/shadow_delta_width -s 0
    xfconf-query -c xfwm4 -p /general/shadow_delta_x -s 0
    xfconf-query -c xfwm4 -p /general/shadow_delta_y -s -3
    xfconf-query -c xfwm4 -p /general/shadow_opacity -s 50
    xfconf-query -c xfwm4 -p /general/show_app_icon -s false
    xfconf-query -c xfwm4 -p /general/show_dock_shadow -s true
    xfconf-query -c xfwm4 -p /general/show_frame_shadow -s true
    xfconf-query -c xfwm4 -p /general/show_popup_shadow -s true
    xfconf-query -c xfwm4 -p /general/snap_resist -s false
    xfconf-query -c xfwm4 -p /general/snap_to_border -s true
    xfconf-query -c xfwm4 -p /general/snap_to_windows -s true
    xfconf-query -c xfwm4 -p /general/snap_width -s 10
    xfconf-query -c xfwm4 -p /general/sync_to_vblank -s true
    xfconf-query -c xfwm4 -p /general/tile_on_move -s true
    xfconf-query -c xfwm4 -p /general/title_alignment -s center
    xfconf-query -c xfwm4 -p /general/title_horizontal_offset -s 0
    xfconf-query -c xfwm4 -p /general/titleless_maximize -s false
    xfconf-query -c xfwm4 -p /general/title_shadow_active -s false
    xfconf-query -c xfwm4 -p /general/title_shadow_inactive -s false
    xfconf-query -c xfwm4 -p /general/title_vertical_offset_active -s 0
    xfconf-query -c xfwm4 -p /general/title_vertical_offset_inactive -s 0
    xfconf-query -c xfwm4 -p /general/toggle_workspaces -s false
    xfconf-query -c xfwm4 -p /general/unredirect_overlays -s true
    xfconf-query -c xfwm4 -p /general/urgent_blink -s false
    xfconf-query -c xfwm4 -p /general/use_compositing -s true
    xfconf-query -c xfwm4 -p /general/vblank_mode -s auto
    xfconf-query -c xfwm4 -p /general/workspace_count -s 5
    xfconf-query -c xfwm4 -p /general/wrap_cycle -s true
    xfconf-query -c xfwm4 -p /general/wrap_layout -s true
    xfconf-query -c xfwm4 -p /general/wrap_resistance -s 10
    xfconf-query -c xfwm4 -p /general/wrap_windows -s false
    xfconf-query -c xfwm4 -p /general/wrap_workspaces -s false
    xfconf-query -c xfwm4 -p /general/zoom_desktop -s true
    xfconf-query -c xfwm4 -p /general/zoom_pointer -s true

    # Desktop
    xfconf-query -c xfce4-desktop -p /desktop-icons/style -s 0

    # Keyboard
    xfconf-query -c keyboards --create -p /Default/KeyRepeat/Delay --type int -s 200
    xfconf-query -c keyboards --create -p /Default/KeyRepeat/Rate --type int -s 50

    # Keybindings
    # -----------
    # Launch apps or actions
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/<Super>d" --type string -s "xfce4-popup-whiskermenu"
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/<Super>p" --type string -s "pavucontrol"
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/commands/custom/<Super>o" --type string -s "xflock4"
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "commands/custom/<Super>Return" --type string -s switch_to_app terminator
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "commands/custom/<Super>w" -s --type string switch_to_app firefox
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>q" --type string -s "close_window_key"

    # # Tiling and maximize windows
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>k" --type string -s maximize_window_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>h" --type string -s tile_left_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>l" --type string -s tile_right_key

    # # Worskapces
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "xfwm4/custom/<Super>comma" --type string -s left_workspace_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "xfwm4/custom/<Super>period" --type string -s right_workspace_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>greater" --type string -s move_window_right_workspace_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>less" --type string -s move_window_left_workspace_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Page_Down" --type string -s next_workspace_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>Page_Up" --type string -s prev_workspace_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>Page_Down" --type string -s move_window_next_workspace_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>Page_Up" --type string -s move_window_prev_workspace_key

    # # Worskapces by numbers
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>1" --type string -s workspace_1_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>2" --type string -s workspace_2_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>3" --type string -s workspace_3_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>4" --type string -s workspace_4_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>5" --type string -s workspace_5_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Super>6" --type string -s workspace_6_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>exclam" --type string -s move_window_workspace_1_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>at" --type string -s move_window_workspace_2_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>numbersign" --type string -s move_window_workspace_3_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>dollar" --type string -s move_window_workspace_4_key
    # xfconf-query -c xfce4-keyboard-shortcuts --create -p "/xfwm4/custom/<Shift><Super>percent" --type string -s move_window_workspace_5_key

    echo ""
    echo "Done! Remember to restart to see the changes."

    echo ""
    echo "TODO:"
    echo "- Check for autostart applications"
    echo "  * devilspie2"
    echo "  * syncthing -m"
    echo "  * disable xcape"
else
    echo "Skipping..."
fi
