#!/bin/bash
#
# ------------------------
# Post installation script
# ------------------------

ask() {
    # Function to ask questions
    #
    # source: https://gist.github.com/davejamesmiller/1965569
    local prompt default reply

    if [[ ${2:-} = 'Y' ]]; then
        prompt='Y/n'
        default='Y'
    elif [[ ${2:-} = 'N' ]]; then
        prompt='y/N'
        default='N'
    else
        prompt='y/n'
        default=''
    fi

    while true; do
        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo -n "$1 [$prompt] "
        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read -r reply </dev/tty
        # Default?
        if [[ -z $reply ]]; then
            reply=$default
        fi
        # Check if the reply is valid
        case "$reply" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}



clear
echo "

 ▄▄▄·      .▄▄ · ▄▄▄▄▄    ▪   ▐ ▄ .▄▄ · ▄▄▄▄▄ ▄▄▄· ▄▄▌  ▄▄▌      .▄▄ ·  ▄▄· ▄▄▄  ▪   ▄▄▄·▄▄▄▄▄
▐█ ▄█▪     ▐█ ▀. •██      ██ •█▌▐█▐█ ▀. •██  ▐█ ▀█ ██•  ██•      ▐█ ▀. ▐█ ▌▪▀▄ █·██ ▐█ ▄█•██
 ██▀· ▄█▀▄ ▄▀▀▀█▄ ▐█.▪    ▐█·▐█▐▐▌▄▀▀▀█▄ ▐█.▪▄█▀▀█ ██▪  ██▪      ▄▀▀▀█▄██ ▄▄▐▀▀▄ ▐█· ██▀· ▐█.▪
▐█▪·•▐█▌.▐▌▐█▄▪▐█ ▐█▌·    ▐█▌██▐█▌▐█▄▪▐█ ▐█▌·▐█ ▪▐▌▐█▌▐▌▐█▌▐▌    ▐█▄▪▐█▐███▌▐█•█▌▐█▌▐█▪·• ▐█▌·
.▀    ▀█▄▀▪ ▀▀▀▀  ▀▀▀     ▀▀▀▀▀ █▪ ▀▀▀▀  ▀▀▀  ▀  ▀ .▀▀▀ .▀▀▀      ▀▀▀▀ ·▀▀▀ .▀  ▀▀▀▀.▀    ▀▀▀

"


# Update system
echo
if ask ":: Update packages?" Y; then
    sudo pacman -Syu
else
    echo "Skipping..."
fi

# Install packages with hornero?
echo
if ask ":: Install packages with hornero?" Y; then
    sudo pacman -S pip
    pip install git+git://github.com/santisoler/hornero.git
    hornero _packages/manjaro.yml
    hornero -p yay _packages/yay.yml
else
    echo "Skipping..."
fi

# Copy dotfiles
echo
if ask ":: Copy the dotfiles to your home folder?" Y; then
    echo "Copying dotfiles [...]"
    # Copy every dotfile in your home directory
    # (except dirs that start with an underscore)
    for directory in [^_]*/; do
        cp -r ${directory%/}/. ~;
    done
else
    echo "Skipping..."
fi

echo
if ask ":: Create symlinks for scripts in ~/bin?" Y; then
    echo "Creating symlinks for any ~/bin/ to ~/local/bin [...]"
    # Create symlinks to ~/bin/ files inside ~/.local/bin
    for binfile in ~/bin/*; do
        ln -s -i $binfile ~/.local/bin;
    done
else
    echo "Skipping..."
fi

echo
if ask ":: Change shell to zsh?" Y; then
    chsh -s /usr/bin/zsh
else
    echo "Skipping..."
fi

echo
if ask ":: Install Neovim plugins?" Y; then
    nvim -c "PlugInstall"
else
    echo "Skipping..."
fi

echo
if ask ":: Download and install mambaforge?" Y; then
    echo "Downloading mambaforge [...]"
    echo "  ** Remember to install in ~/.mambaforge **"
    curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
    bash Mambaforge-$(uname)-$(uname -m).sh
else
    echo "Skipping..."
fi

echo
if ask ":: Customize XFCE appearance?" Y; then
    xfconf-query -c xsettings -p /Net/ThemeName -s "Matcha-dark-sea"
    xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark-Maia"
    xfconf-query -c xsettings -p /Gtk/CursorThemeName -s "xcursor-breeze-snow"
    xfconf-query -c xsettings -p /Gtk/FontName -s "Liberation Sans Regular 10"
    xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "FiraCode Nerd Font Regular 10"
    xfconf-query -c xsettings -p /Gtk/ButtonImages -s false
    xfconf-query -c xfwm4 -p /general/theme -s "Matcha-dark-sea"
    xfconf-query -c xfwm4 -p /general/button_layout -s "|HMC"
    xfconf-query -c xfwm4 -p /general/click_to_focus -s true
    xfconf-query -c xfwm4 -p /general/cycle_apps_only -s false
    xfconf-query -c xfwm4 -p /general/cycle_draw_frame -s true
    xfconf-query -c xfwm4 -p /general/cycle_hidden -s true
    xfconf-query -c xfwm4 -p /general/cycle_minimized -s false
    xfconf-query -c xfwm4 -p /general/cycle_minimum -s true
    xfconf-query -c xfwm4 -p /general/cycle_preview -s false
    xfconf-query -c xfwm4 -p /general/cycle_raise -s false
    xfconf-query -c xfwm4 -p /general/cycle_tabwin_mode -s 0
    xfconf-query -c xfwm4 -p /general/cycle_workspaces -s false
    xfconf-query -c xfwm4 -p /general/easy_click -s Super
    xfconf-query -c keyboards -p /Default/KeyRepeat/Delay -s 245
    xfconf-query -c keyboards -p /Default/KeyRepeat/Rate -s 35
    # Keybindings
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Alt>Print" -s "xfce4-screenshooter -w"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/Print" -s "xfce4-screenshooter"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Shift>Print" -s "xfce4-screenshooter -r"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>d" -s "xfce4-popup-whiskermenu"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>l" -s "xflock4"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>p" -s "pavucontrol"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Alt>Tab" -s "cycle_windows_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Alt><Shift>Tab" -s "cycle_reverse_windows_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Alt>space" -s "popup_menu_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Primary><Super>Down" -s "tile_down_left_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Primary><Super>Left" -s "tile_up_left_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Primary><Super>Right" -s "tile_up_right_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Primary><Super>Up" -s "tile_down_right_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>j" -s "move_window_left_workspace_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>k" -s "move_window_right_workspace_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Page_Down" -s "move_window_next_workspace_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Page_Up" -s "move_window_prev_workspace_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Shift><Super>Up" -s "maximize_window_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Down" -s "tile_down_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>j" -s "left_workspace_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>k" -s "right_workspace_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Left" -s "tile_left_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Page_Down" -s "next_workspace_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Page_Up" -s "prev_workspace_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>q" -s "close_window_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Right" -s "tile_right_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Tab" -s "switch_window_key"
    xfconf-query -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>Up" -s "maximize_window_key"


else
    echo "Skipping..."
fi
