name: default
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - conda-lock # lock environments
  # IPython and Jupyter
  - ipython
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - nbdime # git diffs for notebooks
  - nodejs # needed by jupyterlab
  # Jupyterlab extensions
  - jupyterlab_vim # vim keybindings in jupyterlab
  - jupyterlab_execute_time
  - jupyterlab-git>=0.50
  - jupytext
  - nbqa
  # Software Development
  - livereload
  - pytest
  - black>=22.3
  - isort
  - rope
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-functions
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-simplify
  - pep8-naming
  # Utils
  - tqdm
  # Scientific stack
  - numba
  - dask
  - dask-labextension
  - numpy>=2.0.0
  - matplotlib
  - scipy
  - sympy
  - xarray
  - pandas
  # Geospatial and maps
  - netcdf4
  - rasterio
  - cartopy
  - pyproj
  - pygmt
  - gmt
  # Fatiando
  - ensaio
  - pooch
  - verde
  - harmonica
  - rockhound
  - boule
  # SimPEG
  - simpeg
  - discretize
