name: default
channels:
  - conda-forge
dependencies:
  - python
  - pip
  # IPython and Jupyter
  - ipython
  - jupyter
  - jupyterlab
  - nb_conda
  - jupyterlab_vim # vim keybindings in jupyterlab
  - nbdime # git diffs for notebooks
  - nodejs # needed by jupyterlab
  - conda-lock # lock environments
  # Software Development
  - livereload
  - pytest
  - black>=22.3
  - isort
  - rope
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-functions
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-simplify
  - pep8-naming
  # Scientific stack
  - numba
  - dask
  - dask-labextension
  - numpy
  - matplotlib
  - scipy
  - sympy
  - xarray
  - pandas
  # Geospatial and maps
  - netcdf4
  - cartopy
  - pyproj
  - pygmt
  - gmt
  # Fatiando
  - ensaio
  - pooch
  - verde
  - harmonica
  - rockhound
  - boule
  # SimPEG
  - simpeg
  - discretize
